# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='BatchJobsV1', kernelModule='BATCH_SUBMIT', kernelFunction='SubmitTask', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgGroupBox(name='GroupBox_1', p='DialogBox', text='Mode 1', layout='LAYOUT_FILL_X')
RsgHorizontalFrame(name='HFrame_6', p='GroupBox_1', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgCheckButton(p='HFrame_6', text='enable', keyword='DefaultMode', default=True)
RsgLabel(p='HFrame_6', text='This mode will subnit all jobs in ABAQUS/CAE', useBoldFont=True)
RsgGroupBox(name='GroupBox_2', p='DialogBox', text='Mode 2', layout='LAYOUT_FILL_X')
RsgHorizontalFrame(name='HFrame_2', p='GroupBox_2', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgCheckButton(p='HFrame_2', text='enable', keyword='UserMode', default=False)
RsgCheckButton(p='HFrame_2', text='Only INP file', keyword='pureINP', default=False)
RsgCheckButton(p='HFrame_2', text='Create Job but NOT RUN', keyword='notRUN', default=True)
RsgFileTextField(p='GroupBox_2', ncols=12, labelText='InpFiles:', keyword='InpFilePath', default='', patterns='All files (*)')
RsgSeparator(p='GroupBox_2')
RsgHorizontalFrame(name='HFrame_3', p='GroupBox_2', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgComboBox(name='ComboBox_1', p='HFrame_3', text='jobType', keyword='jobtype', default='ANALYSIS', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_1', text='ANALYSIS')
RsgListItem(p='ComboBox_1', text='RECOVER')
RsgComboBox(name='ComboBox_3', p='HFrame_3', text='ResultFormat', keyword='reFormat', default='ODB', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_3', text='ODB')
RsgListItem(p='ComboBox_3', text='SIM')
RsgListItem(p='ComboBox_3', text='BOTH')
RsgHorizontalFrame(name='HFrame_4', p='GroupBox_2', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgSpinner(p='HFrame_4', text='CpuNum', ncols=7, valueType=INTEGER, increment=1, minValue=1, maxValue=100, keyword='CpuNumber', default=1)
RsgComboBox(name='ComboBox_2', p='HFrame_4', text='MultiProcessMode', keyword='multiprocessMode', default='DEFAULT', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_2', text='DEFAULT')
RsgListItem(p='ComboBox_2', text='MPI')
RsgListItem(p='ComboBox_2', text='THREADS')
RsgGroupBox(name='GroupBox_3', p='GroupBox_2', text='EXPLICIT OPTION', layout='LAYOUT_FILL_X')
RsgHorizontalFrame(name='HFrame_5', p='GroupBox_3', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgComboBox(name='ComboBox_5', p='HFrame_5', text='Parall mode', keyword='Paramode', default='DOMAIN', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_5', text='DOMAIN')
RsgListItem(p='ComboBox_5', text='LOOP')
RsgSpinner(p='HFrame_5', text='DomainNum', ncols=6, valueType=INTEGER, increment=1, minValue=1, maxValue=100, keyword='numDomain', default=1)
dialogBox.show()