# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='QGToolBox', kernelModule='BeamBuider', kernelFunction='BeamBuilder', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgTabBook(name='TabBook_1', p='DialogBox', layout='0')
RsgTabItem(name='TabItem_1', p='TabBook_1', text='BeamBuilder')
RsgCheckButton(p='TabItem_1', text='Enable', keyword='BeamBuilderEnable', default=False)
RsgHorizontalFrame(name='HFrame_5', p='TabItem_1', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgVerticalFrame(name='VFrame_2', p='HFrame_5', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgHorizontalFrame(name='HFrame_6', p='VFrame_2', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgTextField(p='HFrame_6', fieldType='String', ncols=12, labelText='Model=', keyword='ModelName', default='beam')
RsgTextField(p='HFrame_6', fieldType='String', ncols=12, labelText='Part=', keyword='PartName', default='beam-1')
RsgHorizontalFrame(name='HFrame_8', p='VFrame_2', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgComboBox(name='ComboBox_4', p='HFrame_8', text='Meshable=', keyword='Meshable', default='ON', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_4', text='ON')
RsgListItem(p='ComboBox_4', text='OFF')
RsgComboBox(name='ComboBox_3', p='HFrame_8', text='MergeType=', keyword='MergeType', default='Merge', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_3', text='Merge')
RsgListItem(p='ComboBox_3', text='Seperate')
RsgListItem(p='ComboBox_3', text='Imprint')
RsgHorizontalFrame(name='HFrame_4', p='TabItem_1', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgGroupBox(name='GroupBox_2', p='HFrame_4', text='Points', layout='LAYOUT_FILL_X')
RsgTable(p='GroupBox_2', numRows=10, columnData=[('Index', 'Integer', 50), ('X', 'Float', 50), ('Y', 'Float', 50), ('Z', 'Float', 50)], showRowNumbers=True, showGrids=True, keyword='Points', popupFlags='AFXTable.POPUP_CUT|AFXTable.POPUP_COPY|AFXTable.POPUP_PASTE|AFXTable.POPUP_INSERT_ROW|AFXTable.POPUP_DELETE_ROW|AFXTable.POPUP_CLEAR_CONTENTS|AFXTable.POPUP_READ_FROM_FILE|AFXTable.POPUP_WRITE_TO_FILE')
RsgGroupBox(name='GroupBox_3', p='HFrame_4', text='RODS', layout='LAYOUT_FILL_X')
RsgHorizontalFrame(name='HFrame_1', p='GroupBox_3', layout='LAYOUT_FILL_X', pl=0, pr=0, pt=0, pb=0)
RsgTable(p='HFrame_1', numRows=10, columnData=[('RodIndex', 'Integer', 80), ('FirstPoint', 'Integer', 80), ('EndPoint', 'Integer', 80)], showRowNumbers=True, showGrids=True, keyword='Rods', popupFlags='AFXTable.POPUP_CUT|AFXTable.POPUP_COPY|AFXTable.POPUP_PASTE|AFXTable.POPUP_INSERT_ROW|AFXTable.POPUP_DELETE_ROW|AFXTable.POPUP_CLEAR_CONTENTS|AFXTable.POPUP_READ_FROM_FILE|AFXTable.POPUP_WRITE_TO_FILE')
dialogBox.show()