# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='AcousticCheck', kernelModule='AcousticCheck', kernelFunction='AcousticElemSize', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgGroupBox(name='GroupBox_3', p='DialogBox', text='ParameterSetting', layout='LAYOUT_FILL_X')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=22, labelText='Model Demension=', keyword='demension', default='3')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=20, labelText='Min Frequency ( Hz ) =', keyword='minFreq', default='100')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=20, labelText='Max Frequency ( Hz )=', keyword='maxFreq', default='200')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=20, labelText='WaveSpeed ( mm/s )=', keyword='waveSpeed', default='330')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=12, labelText='n =  ', keyword='n', default='8')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=12, labelText='m > ', keyword='m_min', default='0.4')
RsgGroupBox(name='GroupBox_4', p='DialogBox', text='Explain', layout='LAYOUT_FILL_X')
RsgLabel(p='GroupBox_4', text='m: num of wavelengths from source to boundary', useBoldFont=False)
RsgLabel(p='GroupBox_4', text='n: num of internode intervals per wavelengt', useBoldFont=False)
RsgGroupBox(name='GroupBox_5', p='DialogBox', text='Suggest', layout='LAYOUT_FILL_X')
RsgLabel(p='GroupBox_5', text='recommended : n >8 or 10 ; m > 1/3', useBoldFont=True)
dialogBox.show()