# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='RandomFiberRVE', kernelModule='rve', kernelFunction='funKernel', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgHorizontalFrame(name='HFrame_1', p='DialogBox', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgVerticalAligner(name='VAligner_1', p='HFrame_1', pl=0, pr=0, pt=0, pb=0)
RsgTextField(p='VAligner_1', fieldType='String', ncols=12, labelText='dxflib', keyword='dxflib', default='C:\\Python27\\Lib\\site-packages')
RsgTextField(p='VAligner_1', fieldType='String', ncols=12, labelText='Cae_WorkDir', keyword='Cae_WorkDir', default='K:\\202309\\0912')
RsgTextField(p='VAligner_1', fieldType='Float', ncols=12, labelText='vfr', keyword='vfr', default='0.6')
RsgTextField(p='VAligner_1', fieldType='Float', ncols=12, labelText='RVE width', keyword='a', default='100')
RsgTextField(p='VAligner_1', fieldType='Float', ncols=12, labelText='RVE height', keyword='b', default='100')
RsgTextField(p='VAligner_1', fieldType='Float', ncols=12, labelText='RVE deepth', keyword='fiberLength', default='100')
RsgTextField(p='VAligner_1', fieldType='Float', ncols=12, labelText='fiber radius', keyword='r', default='5')
RsgTextField(p='VAligner_1', fieldType='Float', ncols=12, labelText='lmin', keyword='lmin', default='0.5')
RsgTextField(p='VAligner_1', fieldType='Float', ncols=12, labelText='lmax', keyword='lmax', default='1')
RsgTextField(p='VAligner_1', fieldType='Integer', ncols=12, labelText='N', keyword='N', default='500')
RsgTextField(p='VAligner_1', fieldType='String', ncols=12, labelText='dxfFile', keyword='dxfFile', default='rve.dxf')
RsgTextField(p='VAligner_1', fieldType='String', ncols=12, labelText='model', keyword='model', default='Model-1')
RsgTextField(p='VAligner_1', fieldType='String', ncols=12, labelText='FiberPart', keyword='FiberPartName', default='Fiber')
RsgTextField(p='VAligner_1', fieldType='String', ncols=12, labelText='MatrixPart', keyword='MatrixPartName', default='RVEbase')
RsgTextField(p='VAligner_1', fieldType='String', ncols=12, labelText='FiberInstance', keyword='FiberInstanceName', default='Fiber-1')
RsgTextField(p='VAligner_1', fieldType='String', ncols=12, labelText='MatrixInstance', keyword='MatrixInstanceName', default='RVEbase-1')
RsgTextField(p='VAligner_1', fieldType='String', ncols=12, labelText='RVEPart', keyword='RVEPartName', default='RVE')
RsgIcon(p='HFrame_1', fileName=r'icon_randomFiberRVE.png')
dialogBox.show()